services:
  db:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: superheroes
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      SUPERHERO_API_KEY:
      DB_NAME: superhero
      DB_URL: localhost
      DB_USER: admin
      DB_PASSWORD: admin
    restart: unless-stopped

  test:
    build: .
    command: >
      sh -c "
      pip install -r requirements-test.txt &&
      python -m pytest /app/tests -v --tb=short
      "
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    depends_on:
      - db
    environment:
      SUPERHERO_API_KEY:
      DB_NAME: superhero
      DB_URL: localhost
      DB_USER: admin
      DB_PASSWORD: admin

volumes:
  postgres_data: