services:
  db:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: superheroes
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: app
    command: sh -c "pytest /app/app/tests -v --tb=short && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      PYTHONPATH: /app
      SUPERHERO_API_KEY: 7cb82ece0739ea80bfb8d7a3a41116ff
      DB_NAME: superheroes
      DB_URL: db
      DB_USER: admin
      DB_PASSWORD: admin
    restart: unless-stopped

volumes:
  postgres_data: